import { CloudRain, Flame, Waves, Bird, Wind, CloudLightning, Trees, Droplets, AudioWaveform, Zap, Train } from 'lucide-react';
import { AmbientTrack, Reciter } from '../types';

export const AMBIENT_TRACKS: AmbientTrack[] = [
  { id: 'rain', name: 'Light Rain', url: 'https://actions.google.com/sounds/v1/weather/rain_on_roof.ogg', icon: CloudRain },
  { id: 'thunder', name: 'Thunder', url: 'https://actions.google.com/sounds/v1/weather/thunderstorm.ogg', icon: CloudLightning },
  { id: 'birds', name: 'Forest Birds', url: 'https://actions.google.com/sounds/v1/animals/birds_in_forest.ogg', icon: Bird },
  { id: 'fire', name: 'Fireplace', url: 'https://actions.google.com/sounds/v1/ambiences/fire.ogg', icon: Flame },
  { id: 'waves', name: 'Ocean Waves', url: 'https://actions.google.com/sounds/v1/water/waves_crashing_on_rock_beach.ogg', icon: Waves },
  { id: 'wind', name: 'Desert Wind', url: 'https://actions.google.com/sounds/v1/weather/strong_wind.ogg', icon: Wind },
  { id: 'owl', name: 'Night Owl', url: 'https://actions.google.com/sounds/v1/animals/owl_hoot.ogg', icon: Trees },
  { id: 'river', name: 'Flowing River', url: 'https://actions.google.com/sounds/v1/water/river_stream.ogg', icon: Droplets },
  { id: 'whale', name: 'Whale Song', url: 'https://actions.google.com/sounds/v1/animals/whale_song.ogg', icon: AudioWaveform },
  { id: 'crickets', name: 'Crickets', url: 'https://actions.google.com/sounds/v1/animals/crickets_and_night_insects.ogg', icon: Trees },
  { id: 'storm', name: 'Thunderstorm', url: 'https://actions.google.com/sounds/v1/weather/thunderstorm.ogg', icon: Zap },
  { id: 'train', name: 'Train Ride', url: 'https://actions.google.com/sounds/v1/transportation/train_pass_by.ogg', icon: Train },
];

const commons = (file: string) => `https://commons.wikimedia.org/wiki/File:${file}`;

/**
 * Surah file extensions tried, in order, when building a playback URL.
 * MP4 is preferred first, fallback to MP3.
 */
export const AUDIO_FORMATS: string[] = ['mp4', 'mp3'];

export const CURATED_RECITERS: Reciter[] = [
  // ==========================================
  // FEATURED RECITERS (Home Screen Priority)
  // ==========================================
  {
    id: 'noreen',
    name: 'Noreen Muhammad Siddiq',
    nameArabic: 'نورين محمد صديق',
    category: 'Sweet Voices',
    style: "Murattal (Al-Duri 'an Abi 'Amr)",
    location: 'Khartoum',
    region: 'Sudan',
    serverUrl: 'https://server16.mp3quran.net/nourin_siddig/Rewayat-Aldori-A-n-Abi-Amr/',
    bio: "Born in Al-Farajab, North Kordofan, Sudan in 1982. Served as the chief imam of the Grand Mosque of Khartoum and Al-Sayyida Sanhouri Mosque. Celebrated worldwide for his soulful, traditional African pentatonic chanting in the recitation of Al-Duri 'an Abi 'Amr until his passing in 2020.",
    featured: true,
  },
  {
    id: 'jhn',
    name: 'Abdullah Al-Juhany',
    nameArabic: 'عبدالله عواد الجهني',
    category: 'Makkah (Masjid al-Haram)',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server13.mp3quran.net/jhn/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Abdullah_Al_Juhany_%28Cropped%29.png/500px-Abdullah_Al_Juhany_%28Cropped%29.png',
    imageCredit: commons('Abdullah_Al_Juhany_%28Cropped%29.png'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Medina, Saudi Arabia in 1976. Appointed as an official Imam of Masjid al-Haram in Mecca in 2007 after previously leading prayers at Masjid al-Qiblatain and the Prophet Mosque in Medina. Renowned for his melodious, fluent Hafs recitation and exceptional tajweed mastery.',
    featured: true,
  },

  // ==========================================
  // MADINAH (PROPHET\'S MOSQUE)
  // ==========================================
  {
    id: 'hthfi',
    name: 'Ali Alhuthaifi',
    nameArabic: 'علي بن عبدالرحمن الحذيفي',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server9.mp3quran.net/hthfi/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ali_al-Hudhayfi.jpg/500px-Ali_al-Hudhayfi.jpg',
    imageCredit: commons('Ali_al-Hudhayfi.jpg'),
    imageLicense: 'Public domain',
    bio: "Born in Al-Qarn Al-Mustaqeem, Saudi Arabia in 1947. Appointed as Chief Imam of the Prophet's Mosque in Medina in 1979 and previously led Taraweeh at Masjid al-Haram. Renowned for his deliberate, measured recitation adhering strictly to classical tajweed rules.",
  },
  {
    id: 'budair',
    name: 'Salah Al-Budair',
    nameArabic: 'صلاح بن محمد البدير',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server6.mp3quran.net/s_bud/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Salah_Ibn_Mohammed_Al_Budair.jpg/500px-Salah_Ibn_Mohammed_Al_Budair.jpg',
    imageCredit: commons('Salah_Ibn_Mohammed_Al_Budair.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: "Born in Al-Hofuf, Al-Ahsa, Saudi Arabia in 1970. Appointed as an Imam and Khateeb of the Prophet's Mosque in Medina in 1998, and also serves as a judge at the High Court in Medina. Known for his deeply moving, emotional, and composed recitation during daily prayers and Taraweeh.",
  },
  {
    id: 'thubti',
    name: 'Abdulbari Ath-Thubaity',
    nameArabic: 'عبدالبارئ بن عواض الثبيتي',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server6.mp3quran.net/thubti/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Abdulbari_ath-Thubaity_delivering_sermon_at_Prophet%27s_Mosque_Medina.jpg/500px-Abdulbari_ath-Thubaity_delivering_sermon_at_Prophet%27s_Mosque_Medina.jpg',
    imageCredit: commons('Abdulbari_ath-Thubaity_delivering_sermon_at_Prophet%27s_Mosque_Medina.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: "Born in Mecca, Saudi Arabia in 1960. Has served as an Imam and Khateeb of the Prophet's Mosque in Medina since 1993, after previously leading Taraweeh at Masjid al-Haram in Mecca. Renowned for his distinct, reverent vocal timbre and eloquent sermon delivery.",
  },
  {
    id: 'qasm',
    name: 'Abdulmohsen Al-Qasim',
    nameArabic: 'عبدالمحسن بن محمد القاسم',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server8.mp3quran.net/qasm/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Abdul_Mohsin_Al-Qasim.jpg/500px-Abdul_Mohsin_Al-Qasim.jpg',
    imageCredit: commons('Abdul_Mohsin_Al-Qasim.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: "Born in Mecca, Saudi Arabia in 1968. Appointed as an Imam and Khateeb of the Prophet's Mosque in Medina in 1997, and serves as a judge in Medina's Sharia Court. Celebrated for his serene, precise recitation and extensive Islamic scholarship.",
  },
  {
    id: 'buajan',
    name: 'Abdullah Al-Buayjan',
    nameArabic: 'عبدالله بن عبدالرحمن البعيجان',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server8.mp3quran.net/buajan/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Abdullah_bin_Abdur_Rahman_Al-Buayjan_Imam_of_Masjid_an-Nabawi_meets_Sheikh_Hasina_2023-10-29_%28PID-0012739%29.jpg/500px-Abdullah_bin_Abdur_Rahman_Al-Buayjan_Imam_of_Masjid_an-Nabawi_meets_Sheikh_Hasina_2023-10-29_%28PID-0012739%29.jpg',
    imageCredit: commons('Abdullah_bin_Abdur_Rahman_Al-Buayjan_Imam_of_Masjid_an-Nabawi_meets_Sheikh_Hasina_2023-10-29_(PID-0012739).jpg'),
    imageLicense: 'Public domain',
    bio: "Born in Saudi Arabia and holds a doctorate in Islamic jurisprudence from Imam Muhammad Ibn Saud Islamic University. Appointed as an Imam of the Prophet's Mosque in Medina in 2013 and later appointed as Khateeb. Celebrated for his steady, resonant recitation and eloquently structured Friday sermons.",
  },
  {
    id: 'ahmad_huth',
    name: 'Ahmad Al-Hudhaify',
    nameArabic: 'أحمد بن علي الحذيفي',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server8.mp3quran.net/ahmad_huth/',
    bio: "Born in Medina, Saudi Arabia, son of Chief Imam Sheikh Ali Al-Hudhaify. Serves as Imam and Khateeb of Quba Mosque and has been appointed to lead prayers at the Prophet's Mosque in Medina. Recites with a disciplined, calming cadence strongly echoing the classic Medinan style.",
  },
  {
    id: 'mohna',
    name: 'Khalid Al-Muhanna',
    nameArabic: 'خالد بن سليمان المهنا',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server11.mp3quran.net/mohna/',
    bio: "Born in Al-Ahsa, Saudi Arabia and earned a doctorate from the College of Hadith. Appointed as an Imam of the Prophet's Mosque in Medina in 2019. Known for his clear articulation, soothing acoustic tone, and adherence to strict classical tajweed.",
  },
  {
    id: 'barhaji',
    name: 'Muhammad Barhaji',
    nameArabic: 'محمد برهجي',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server16.mp3quran.net/M_Burhaji/Rewayat-Hafs-A-n-Assem/',
    bio: "Prominent Quran reciter based in Medina, Saudi Arabia. Regularly leads prayers in Medina and participates in Quranic teaching circles. Characterized by a warm, contemplative recitation following the Hafs 'an 'Asim riwayah.",
  },
  {
    id: 'qarafi',
    name: 'Abdullah Al-Qarafi',
    nameArabic: 'عبدالله القرافي',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server16.mp3quran.net/a_alqrafi/Rewayat-Hafs-A-n-Assem/',
    bio: "Imam and reciter in Medina, Saudi Arabia. Known for leading Taraweeh and Tahajjud prayers in mosques across the holy city of Medina. Recites with a gentle, humble rhythm deeply rooted in the Medinan tradition.",
  },
  {
    id: 'bader',
    name: 'Badr Al-Turki',
    nameArabic: 'بدر بن محمد التركي',
    category: "Madinah (Prophet's Mosque)",
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server10.mp3quran.net/bader/Rewayat-Hafs-A-n-Assem/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Photo_of_badr_al-turki_in_2023.jpg/500px-Photo_of_badr_al-turki_in_2023.jpg',
    imageCredit: commons('Photo_of_badr_al-turki_in_2023.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: "Born in Saudi Arabia and leads prayers in Medina. Appointed as an imam for Taraweeh prayers at the Prophet's Mosque in Medina in 2024. Renowned for his gentle, melodic delivery and tranquil recitation.",
  },

  // ==========================================
  // MAKKAH (MASJID AL-HARAM)
  // ==========================================
  {
    id: 'sds',
    name: 'Abdul Rahman Al-Sudais',
    nameArabic: 'عبدالرحمن بن عبدالعزيز السديس',
    category: 'Makkah (Masjid al-Haram)',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server11.mp3quran.net/sds/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg/500px-Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg',
    imageCredit: commons('Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg'),
    imageLicense: 'CC BY-SA 3.0',
    bio: "Born in Riyadh, Saudi Arabia in 1960. Appointed as an Imam of Masjid al-Haram in Mecca in 1984 and later as President of the General Presidency for the Affairs of the Two Holy Mosques. Known worldwide for his emotional, passionate recitation and distinctive vocal pitch.",
  },
  {
    id: 'shrm',
    name: 'Saud Al-Shuraim',
    nameArabic: 'سعود بن إبراهيم الشريم',
    category: 'Makkah (Masjid al-Haram)',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server7.mp3quran.net/shur/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Saud_Shuraim_doing_the_Khutbah.png/500px-Saud_Shuraim_doing_the_Khutbah.png',
    imageCredit: commons('Saud_Shuraim_doing_the_Khutbah.png'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Riyadh, Saudi Arabia in 1966. Served as an Imam and Khateeb of Masjid al-Haram in Mecca from 1991 to 2022. Renowned for his deep, dignified tone and commanding mastery of classical maqamat.',
  },
  {
    id: 'maher',
    name: 'Maher Al-Muaiqly',
    nameArabic: 'ماهر بن حمد المعيقلي',
    category: 'Makkah (Masjid al-Haram)',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server12.mp3quran.net/maher/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Maher_Al_Mueaqly.jpg/500px-Maher_Al_Mueaqly.jpg',
    imageCredit: commons('Maher_Al_Mueaqly.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Medina, Saudi Arabia in 1969. Has served as an Imam and Khateeb of Masjid al-Haram in Mecca since 2007. Famous globally for his clear, warm, and highly recognizable recitation tempo.',
  },
  {
    id: 'balila',
    name: 'Bandar Baleela',
    nameArabic: 'بندر بن عبدالعزيز بليلة',
    category: 'Makkah (Masjid al-Haram)',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server6.mp3quran.net/balilah/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Bandar_Baleela.jpg/500px-Bandar_Baleela.jpg',
    imageCredit: commons('Bandar_Baleela.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Mecca, Saudi Arabia in 1975. Appointed as an Imam of Masjid al-Haram in Mecca in 2013 and also appointed to the Council of Senior Scholars. Revered for his velvety, melodious tone and precise adherence to the Hijazi recitation style.',
  },

  // ==========================================
  // CLASSIC MASTERS
  // ==========================================
  {
    id: 'basit',
    name: 'Abdulbasit Abdulsamad',
    nameArabic: 'عبدالباسط بن محمد عبدالصمد',
    category: 'Classic Masters',
    style: 'Mujawwad',
    location: 'Cairo',
    region: 'Egypt',
    serverUrl: 'https://server7.mp3quran.net/basit/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg/500px-Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg',
    imageCredit: commons('Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: "Born in Armant, Qena Governorate, Egypt in 1927. Served as the official reciter of Al-Imam Al-Shafi'i and Al-Hussein Mosques in Cairo. Celebrated as the Golden Throat whose breathtaking breath control and harmonic genius captivated listeners worldwide.",
  },
  {
    id: 'husary',
    name: 'Mahmoud Khalil Al-Husary',
    nameArabic: 'محمود خليل الحصري',
    category: 'Classic Masters',
    style: 'Murattal',
    location: 'Tanta',
    region: 'Egypt',
    serverUrl: 'https://server13.mp3quran.net/husr/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Hussary.jpg/500px-Hussary.jpg',
    imageCredit: commons('Hussary.jpg'),
    imageLicense: 'Public domain',
    bio: 'Born in Tanta, Gharbia Governorate, Egypt in 1917. Served as Shaykh al-Maqari (Head of Reciters) of Egypt and was the first reciter to record the complete Quran in murattal style for Egyptian radio in 1961. Universally regarded as the benchmark of flawless tajweed, precise cadence, and authentic vocal phonetics.',
  },
  {
    id: 'minshawi',
    name: 'Muhammad Siddiq Al-Minshawi',
    nameArabic: 'محمد صديق المنشاوي',
    category: 'Classic Masters',
    style: 'Murattal',
    location: 'Sohag',
    region: 'Egypt',
    serverUrl: 'https://server10.mp3quran.net/minsh/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Elminshwey.jpg/500px-Elminshwey.jpg',
    imageCredit: commons('Elminshwey.jpg'),
    imageLicense: 'Public domain',
    bio: 'Born in Al-Manshah, Sohag Governorate, Egypt in 1920 to an esteemed lineage of Quranic reciters. Led prayers and recited at major mosques across the Arab world including Al-Aqsa Mosque in Jerusalem. Beloved as Al-Sawt Al-Baki (The Weeping Voice) for his profoundly emotional, heart-rending Quranic delivery.',
  },
  {
    id: 'mustafa',
    name: 'Mustafa Ismail',
    nameArabic: 'مصطفى إسماعيل',
    category: 'Classic Masters',
    style: 'Mujawwad',
    location: 'Cairo',
    region: 'Egypt',
    serverUrl: 'https://server8.mp3quran.net/mustafa/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/%D8%A7%D9%84%D8%B4%D9%8A%D8%AE_%D9%85%D8%B5%D8%B7%D9%81%D9%89_%D8%A5%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%841.jpg/500px-%D8%A7%D9%84%D8%B4%D9%8A%D8%AE_%D9%85%D8%B5%D8%B7%D9%81%D9%89_%D8%A5%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%841.jpg',
    imageCredit: commons('%D8%A7%D9%84%D8%B4%D9%8A%D8%AE_%D9%85%D8%B5%D8%B7%D9%81%D9%89_%D8%A5%D8%B3%D9%85%D8%A7%D8%B9%D9%8A%D9%841.jpg'),
    imageLicense: 'Public domain',
    bio: 'Born in Mit Ghazal, Gharbia Governorate, Egypt in 1905. Served as the official reciter of Al-Azhar Mosque and Royal Palace reciter under King Farouk. Master of vocal maqamat whose extraordinary improvisational depth and rhythmic majesty transformed 20th-century Quranic recitation.',
  },
  {
    id: 'shatri',
    name: 'Abu Bakr Ash-Shatri',
    nameArabic: 'شيخ أبو بكر الشاطري',
    category: 'Classic Masters',
    style: 'Murattal',
    location: 'Jeddah',
    region: 'Saudi Arabia',
    serverUrl: 'https://server11.mp3quran.net/shatri/',
    bio: 'Born in Jeddah, Saudi Arabia in 1970 and received ijazah in Quran recitation under Sheikh Ayman Suwayd. Has led prayers in major mosques across Jeddah, Riyadh, Dubai, and Bahrain. Celebrated across the Muslim world for his warm, smooth, and easily followed murattal style.',
  },

  // ==========================================
  // SWEET VOICES
  // ==========================================
  {
    id: 'afs',
    name: 'Mishary Rashid Alafasy',
    nameArabic: 'مشاري بن راشد العفاسي',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Kuwait City',
    region: 'Kuwait',
    serverUrl: 'https://server8.mp3quran.net/afs/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg/500px-%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg',
    imageCredit: commons('%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg'),
    imageLicense: 'CC BY-SA 3.0',
    bio: 'Born in Kuwait City in 1976 and studied at the College of the Holy Quran in the Islamic University of Madinah. Leads Taraweeh prayers annually at the Grand Mosque of Kuwait and internationally. Renowned for his sweet, melodious tone and crystal-clear pronunciation.',
  },
  {
    id: 'yasser',
    name: 'Yasser Al-Dosari',
    nameArabic: 'ياسر بن راشد الدوسري',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server11.mp3quran.net/yasser/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Yasser_Al-Dosari_%28cropped%29.jpg/500px-Yasser_Al-Dosari_%28cropped%29.jpg',
    imageCredit: commons('Yasser_Al-Dosari_%28cropped%29.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Al-Kharj, Saudi Arabia in 1980. Appointed as an Imam and Khateeb of Masjid al-Haram in Mecca in 2019 after years of leading Taraweeh. Celebrated for his powerful, soaring pitch, emotional depth, and immaculate vocal resonance.',
  },
  {
    id: 'ghamdi',
    name: 'Saad Al-Ghamdi',
    nameArabic: 'سعد بن سعيد الغامدي',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Dammam',
    region: 'Saudi Arabia',
    serverUrl: 'https://server7.mp3quran.net/s_gmd/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Saad_al_Ghamdi.jpg/500px-Saad_al_Ghamdi.jpg',
    imageCredit: commons('Saad_al_Ghamdi.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: "Born in Dammam, Eastern Province, Saudi Arabia in 1967. Served as an Imam for Taraweeh prayers at the Prophet's Mosque in Medina in 2009 and at Kanoo Mosque in Dammam. Renowned for his crystalline, vibrant tone and widely distributed international Quranic recordings.",
  },
  {
    id: 'qatami',
    name: 'Nasser Al-Qatami',
    nameArabic: 'ناصر بن علي القطامي',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Riyadh',
    region: 'Saudi Arabia',
    serverUrl: 'https://server6.mp3quran.net/qtm/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/%D8%B5%D9%88%D8%B1%D8%A9_%D8%B4%D8%AE%D8%B5%D9%8A%D8%A9_%D9%86%D8%A7%D8%B5%D8%B1_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%85%D9%8A.jpg/500px-%D8%B5%D9%88%D8%B1%D8%A9_%D8%B4%D8%AE%D8%B5%D9%8A%D8%A9_%D9%86%D8%A7%D8%B5%D8%B1_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%85%D9%8A.jpg',
    imageCredit: commons('%D8%A5%D9%85%D8%A7%D9%85_%D9%86%D8%A7%D8%B5%D8%B1_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%85%D9%8A.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Riyadh, Saudi Arabia in 1980. Serves as the Imam and Khateeb of Princess Latifa bint Sultan Mosque in Riyadh. Famous across the Arab world for his tender, emotional voice and captivating recitation tempo.',
  },
  {
    id: 'wadee',
    name: 'Wadee Hammadi Al-Yamani',
    nameArabic: 'وديع حمادي اليمني',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Aden',
    region: 'Yemen',
    serverUrl: 'https://server6.mp3quran.net/wdee3/',
    bio: "Born in Aden, Yemen and obtained a bachelor's degree in Islamic studies from the University of Science and Technology in Sana'a. Has led Taraweeh and Qiyam prayers at prominent mosques in Kuwait and Dubai. Known for his soothing, calm melodic style and clear tajweed.",
  },
  {
    id: 'hazza',
    name: 'Hazza Al-Balushi',
    nameArabic: 'هزاع بن عبدالله البلوشي',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Liwa',
    region: 'Oman',
    serverUrl: 'https://server11.mp3quran.net/hazza/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/%D9%87%D8%B2%D8%A7%D8%B9_%D8%A7%D9%84%D8%A8%D9%84%D9%88%D8%B4%D9%8A.jpg/500px-%D9%87%D8%B2%D8%A7%D8%B9_%D8%A7%D9%84%D8%A8%D9%84%D9%88%D8%B4%D9%8A.jpg',
    imageCredit: commons('%D9%87%D8%B2%D8%A7%D8%B9_%D8%A7%D9%84%D8%A8%D9%84%D9%88%D8%B4%D9%8A.jpg'),
    imageLicense: 'CC BY-SA 4.0',
    bio: 'Born in Liwa, North Al Batinah Governorate, Oman in 1995. Studied economic sciences at Sultan Qaboos University and has led prayers in several Gulf countries. Beloved among young listeners for his gentle, heart-touching timbre and distinctive Omani inflection.',
  },
  {
    id: 'edghouch',
    name: 'Yusuf Edghouch',
    nameArabic: 'يوسف الدغوش',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Rabat',
    region: 'Morocco',
    serverUrl: 'https://server7.mp3quran.net/dgsh/',
    bio: 'Born in Morocco and currently active as an imam and Quran instructor in the United States. Has led Taraweeh prayers in multiple community Islamic centers across North America. Celebrated for his resonant, deeply peaceful tone blending classical Moroccan and eastern maqam aesthetics.',
  },
  {
    id: 'mansor',
    name: 'Mansoor Al-Salemi',
    nameArabic: 'منصور السالمي',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Jeddah',
    region: 'Saudi Arabia',
    serverUrl: 'https://server14.mp3quran.net/mansor/',
    bio: 'Born in Jeddah, Saudi Arabia. Well known Islamic preacher, speaker, and Quran reciter who has led prayers in various mosques in Saudi Arabia and the UAE. Famous for his expressive, heartfelt recitation style and moving sermons.',
  },
  {
    id: 'okasha',
    name: 'Okasha Kameny',
    nameArabic: 'عكاشة كميني',
    category: 'Sweet Voices',
    style: 'Murattal (Ibn Kathir)',
    location: 'Kumasi',
    region: 'Ghana',
    serverUrl: 'https://server16.mp3quran.net/okasha/Rewayat-Albizi-A-n-Ibn-Katheer/',
    bio: 'Born in Kumasi, Ghana and studied Islamic sciences in Medina. Serves as an imam and educator in the United States. Widely renowned for his mastery of the ten Qira’at, especially the Riwayah of Al-Bazzi from Ibn Kathir.',
  },
  {
    id: 'lhdan',
    name: 'Muhammad Al-Luhaidan',
    nameArabic: 'محمد بن إبراهيم اللحيدان',
    category: 'Sweet Voices',
    style: 'Murattal',
    location: 'Riyadh',
    region: 'Saudi Arabia',
    serverUrl: 'https://server8.mp3quran.net/lhdan/',
    bio: 'Born in Riyadh, Saudi Arabia and serves as a judge and former imam of Al-Nasir Mosque in Riyadh. Celebrated across the Muslim world for his emotional, tearful recitation style that resonates deeply with audiences during Qiyam al-Layl.',
  },
];

export const DEFAULT_RECITER_ID = 'noreen';
