import { CloudRain, Flame, Waves, Bird, Wind, CloudLightning, Trees, Droplets, AudioWaveform, Zap, Train } from 'lucide-react';
import { AmbientTrack, Reciter } from '../types';

export const AMBIENT_TRACKS: AmbientTrack[] = [
  { id: 'rain', name: 'Light Rain', url: 'https://actions.google.com/sounds/v1/weather/rain_on_roof.ogg', icon: CloudRain },
  { id: 'thunder', name: 'Thunder', url: 'https://actions.google.com/sounds/v1/weather/thunderstorm.ogg', icon: CloudLightning },
  { id: 'birds', name: 'Forest Birds', url: 'https://actions.google.com/sounds/v1/animals/birds_in_forest.ogg', icon: Bird },
  { id: 'fire', name: 'Fireplace', url: 'https://actions.google.com/sounds/v1/ambiences/fire.ogg', icon: Flame },
  { id: 'waves', name: 'Ocean Waves', url: 'https://actions.google.com/sounds/v1/water/waves_crashing_on_rock_beach.ogg', icon: Waves },
  { id: 'wind', name: 'Desert Wind', url: 'https://actions.google.com/sounds/v1/weather/strong_wind.ogg', icon: Wind },
  { id: 'owl', name: 'Night Owl', url: 'https://actions.google.com/sounds/v1/animals/owl_hoot.ogg', icon: Trees },
  { id: 'river', name: 'Flowing River', url: 'https://actions.google.com/sounds/v1/water/river_stream.ogg', icon: Droplets },
  { id: 'whale', name: 'Whale Song', url: 'https://actions.google.com/sounds/v1/animals/whale_song.ogg', icon: AudioWaveform },
  { id: 'crickets', name: 'Crickets', url: 'https://actions.google.com/sounds/v1/animals/crickets_and_night_insects.ogg', icon: Trees },
  { id: 'storm', name: 'Thunderstorm', url: 'https://actions.google.com/sounds/v1/weather/thunderstorm.ogg', icon: Zap },
  { id: 'train', name: 'Train Ride', url: 'https://actions.google.com/sounds/v1/transportation/train_pass_by.ogg', icon: Train },
];

const commons = (file: string) => `https://commons.wikimedia.org/wiki/File:${file}`;

export const CURATED_RECITERS: Reciter[] = [
  {
    id: 'afs',
    name: 'Mishary Rashid Alafasy',
    style: 'Murattal',
    location: 'Kuwait',
    region: 'Kuwait',
    serverUrl: 'https://server8.mp3quran.net/afs/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg/500px-%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg',
    imageCredit: commons('%D0%9C%D0%B8%D1%88%D0%B0%D1%80%D0%B8_%D0%A0%D0%B0%D1%88%D0%B8%D0%B4.jpg'),
  },
  {
    id: 'sds',
    name: 'Abdul Rahman Al-Sudais',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server11.mp3quran.net/sds/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg/500px-Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg',
    imageCredit: commons('Abdul-Rahman_Al-Sudais_%28Cropped%2C_2011%29.jpg'),
  },
  {
    id: 'shrm',
    name: 'Saud Al-Shuraim',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server7.mp3quran.net/shrm/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Saud_Shuraim_doing_the_Khutbah.png/500px-Saud_Shuraim_doing_the_Khutbah.png',
    imageCredit: commons('Saud_Shuraim_doing_the_Khutbah.png'),
  },
  {
    id: 'maher',
    name: 'Maher Al-Muaiqly',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server12.mp3quran.net/maher/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Maher_Al_Mueaqly.jpg/500px-Maher_Al_Mueaqly.jpg',
    imageCredit: commons('Maher_Al_Mueaqly.jpg'),
  },
  {
    id: 'yasser',
    name: 'Yasser Al-Dosari',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server11.mp3quran.net/yasser/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Yasser_Al-Dosari_%28cropped%29.jpg/500px-Yasser_Al-Dosari_%28cropped%29.jpg',
    imageCredit: commons('Yasser_Al-Dosari_%28cropped%29.jpg'),
  },
  {
    id: 'balila',
    name: 'Bandar Baleela',
    style: 'Murattal',
    location: 'Mecca',
    region: 'Saudi Arabia',
    serverUrl: 'https://server6.mp3quran.net/balila/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Bandar_Baleela.jpg/500px-Bandar_Baleela.jpg',
    imageCredit: commons('Bandar_Baleela.jpg'),
  },
  {
    id: 'hthfi',
    name: 'Ali Alhuthaifi',
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server9.mp3quran.net/hthfi/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ali_al-Hudhayfi.jpg/500px-Ali_al-Hudhayfi.jpg',
    imageCredit: commons('Ali_al-Hudhayfi.jpg'),
  },
  {
    id: 'qasm',
    name: 'Abdulmohsen Al Qasim',
    style: 'Murattal',
    location: 'Medina',
    region: 'Saudi Arabia',
    serverUrl: 'https://server8.mp3quran.net/qasm/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Abdul_Mohsin_Al-Qasim.jpg/500px-Abdul_Mohsin_Al-Qasim.jpg',
    imageCredit: commons('Abdul_Mohsin_Al-Qasim.jpg'),
  },
  {
    id: 'basit',
    name: 'Abdulbasit Abdulsamad',
    style: 'Mujawwad',
    location: 'Egypt',
    region: 'Egypt',
    serverUrl: 'https://server7.mp3quran.net/basit/',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg/500px-Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg',
    imageCredit: commons('Abdul_Basit_Abdul_Samad_at_Centenary_Celebration_Of_Darul_Uloom_Deoband_1980.jpg'),
  },
];

export const DEFAULT_RECITER_ID = 'afs';
