import { Chapter } from '../types';

export const ALL_SURAHS: Chapter[] = [
  { id: 1, name_simple: 'Al-Fatihah', name_arabic: 'الفاتحة', translated_name: { name: 'The Opener' }, verses_count: 7 },
  { id: 2, name_simple: 'Al-Baqarah', name_arabic: 'البقرة', translated_name: { name: 'The Cow' }, verses_count: 286 },
  { id: 3, name_simple: "Ali 'Imran", name_arabic: 'آل عمران', translated_name: { name: 'Family of Imran' }, verses_count: 200 },
  { id: 4, name_simple: 'An-Nisa', name_arabic: 'النساء', translated_name: { name: 'The Women' }, verses_count: 176 },
  { id: 5, name_simple: "Al-Ma'idah", name_arabic: 'المائدة', translated_name: { name: 'The Table Spread' }, verses_count: 120 },
  { id: 6, name_simple: "Al-An'am", name_arabic: 'الأنعام', translated_name: { name: 'The Cattle' }, verses_count: 165 },
  { id: 7, name_simple: "Al-A'raf", name_arabic: 'الأعراف', translated_name: { name: 'The Heights' }, verses_count: 206 },
  { id: 8, name_simple: 'Al-Anfal', name_arabic: 'الأنفال', translated_name: { name: 'The Spoils of War' }, verses_count: 75 },
  { id: 9, name_simple: 'At-Tawbah', name_arabic: 'التوبة', translated_name: { name: 'The Repentance' }, verses_count: 129 },
  { id: 10, name_simple: 'Yunus', name_arabic: 'يونس', translated_name: { name: 'Jonah' }, verses_count: 109 },
  { id: 11, name_simple: 'Hud', name_arabic: 'هود', translated_name: { name: 'Hud' }, verses_count: 123 },
  { id: 12, name_simple: 'Yusuf', name_arabic: 'يوسف', translated_name: { name: 'Joseph' }, verses_count: 111 },
  { id: 13, name_simple: "Ar-Ra'd", name_arabic: 'الرعد', translated_name: { name: 'The Thunder' }, verses_count: 43 },
  { id: 14, name_simple: 'Ibrahim', name_arabic: 'ابراهيم', translated_name: { name: 'Abraham' }, verses_count: 52 },
  { id: 15, name_simple: 'Al-Hijr', name_arabic: 'الحجر', translated_name: { name: 'The Rocky Tract' }, verses_count: 99 },
  { id: 16, name_simple: 'An-Nahl', name_arabic: 'النحل', translated_name: { name: 'The Bee' }, verses_count: 128 },
  { id: 17, name_simple: 'Al-Isra', name_arabic: 'الإسراء', translated_name: { name: 'The Night Journey' }, verses_count: 111 },
  { id: 18, name_simple: 'Al-Kahf', name_arabic: 'الكهف', translated_name: { name: 'The Cave' }, verses_count: 110 },
  { id: 19, name_simple: 'Maryam', name_arabic: 'مريم', translated_name: { name: 'Mary' }, verses_count: 98 },
  { id: 20, name_simple: 'Taha', name_arabic: 'طه', translated_name: { name: 'Ta-Ha' }, verses_count: 135 },
  { id: 21, name_simple: 'Al-Anbiya', name_arabic: 'الأنبياء', translated_name: { name: 'The Prophets' }, verses_count: 112 },
  { id: 22, name_simple: 'Al-Hajj', name_arabic: 'الحج', translated_name: { name: 'The Pilgrimage' }, verses_count: 78 },
  { id: 23, name_simple: "Al-Mu'minun", name_arabic: 'المؤمنون', translated_name: { name: 'The Believers' }, verses_count: 118 },
  { id: 24, name_simple: 'An-Nur', name_arabic: 'النور', translated_name: { name: 'The Light' }, verses_count: 64 },
  { id: 25, name_simple: 'Al-Furqan', name_arabic: 'الفرقان', translated_name: { name: 'The Criterion' }, verses_count: 77 },
  { id: 26, name_simple: "Ash-Shu'ara", name_arabic: 'الشعراء', translated_name: { name: 'The Poets' }, verses_count: 227 },
  { id: 27, name_simple: 'An-Naml', name_arabic: 'النمل', translated_name: { name: 'The Ant' }, verses_count: 93 },
  { id: 28, name_simple: 'Al-Qasas', name_arabic: 'القصص', translated_name: { name: 'The Stories' }, verses_count: 88 },
  { id: 29, name_simple: "Al-'Ankabut", name_arabic: 'العنكبوت', translated_name: { name: 'The Spider' }, verses_count: 69 },
  { id: 30, name_simple: 'Ar-Rum', name_arabic: 'الروم', translated_name: { name: 'The Romans' }, verses_count: 60 },
  { id: 31, name_simple: 'Luqman', name_arabic: 'لقمان', translated_name: { name: 'Luqman' }, verses_count: 34 },
  { id: 32, name_simple: 'As-Sajdah', name_arabic: 'السجدة', translated_name: { name: 'The Prostration' }, verses_count: 30 },
  { id: 33, name_simple: 'Al-Ahzab', name_arabic: 'الأحزاب', translated_name: { name: 'The Combined Forces' }, verses_count: 73 },
  { id: 34, name_simple: 'Saba', name_arabic: 'سبإ', translated_name: { name: 'Sheba' }, verses_count: 54 },
  { id: 35, name_simple: 'Fatir', name_arabic: 'فاطر', translated_name: { name: 'Originator' }, verses_count: 45 },
  { id: 36, name_simple: 'Ya-Sin', name_arabic: 'يس', translated_name: { name: 'Ya Sin' }, verses_count: 83 },
  { id: 37, name_simple: 'As-Saffat', name_arabic: 'الصافات', translated_name: { name: 'Those who set the Ranks' }, verses_count: 182 },
  { id: 38, name_simple: 'Sad', name_arabic: 'ص', translated_name: { name: 'The Letter Saad' }, verses_count: 88 },
  { id: 39, name_simple: 'Az-Zumar', name_arabic: 'الزمر', translated_name: { name: 'The Troops' }, verses_count: 75 },
  { id: 40, name_simple: 'Ghafir', name_arabic: 'غافر', translated_name: { name: 'The Forgiver' }, verses_count: 85 },
  { id: 41, name_simple: 'Fussilat', name_arabic: 'فصلت', translated_name: { name: 'Explained in Detail' }, verses_count: 54 },
  { id: 42, name_simple: 'Ash-Shuraa', name_arabic: 'الشورى', translated_name: { name: 'The Consultation' }, verses_count: 53 },
  { id: 43, name_simple: 'Az-Zukhruf', name_arabic: 'الزخرف', translated_name: { name: 'The Ornaments of Gold' }, verses_count: 89 },
  { id: 44, name_simple: 'Ad-Dukhan', name_arabic: 'الدخان', translated_name: { name: 'The Smoke' }, verses_count: 59 },
  { id: 45, name_simple: 'Al-Jathiyah', name_arabic: 'الجاثية', translated_name: { name: 'The Crouching' }, verses_count: 37 },
  { id: 46, name_simple: 'Al-Ahqaf', name_arabic: 'الأحقاف', translated_name: { name: 'The Wind-Curved Sandhills' }, verses_count: 35 },
  { id: 47, name_simple: 'Muhammad', name_arabic: 'محمد', translated_name: { name: 'Muhammad' }, verses_count: 38 },
  { id: 48, name_simple: 'Al-Fath', name_arabic: 'الفتح', translated_name: { name: 'The Victory' }, verses_count: 29 },
  { id: 49, name_simple: 'Al-Hujurat', name_arabic: 'الحجرات', translated_name: { name: 'The Rooms' }, verses_count: 18 },
  { id: 50, name_simple: 'Qaf', name_arabic: 'ق', translated_name: { name: 'The Letter Qaf' }, verses_count: 45 },
  { id: 51, name_simple: 'Adh-Dhariyat', name_arabic: 'الذاريات', translated_name: { name: 'The Winnowing Winds' }, verses_count: 60 },
  { id: 52, name_simple: 'At-Tur', name_arabic: 'الطور', translated_name: { name: 'The Mount' }, verses_count: 49 },
  { id: 53, name_simple: 'An-Najm', name_arabic: 'النجم', translated_name: { name: 'The Star' }, verses_count: 62 },
  { id: 54, name_simple: 'Al-Qamar', name_arabic: 'القمر', translated_name: { name: 'The Moon' }, verses_count: 55 },
  { id: 55, name_simple: 'Ar-Rahman', name_arabic: 'الرحمن', translated_name: { name: 'The Beneficent' }, verses_count: 78 },
  { id: 56, name_simple: "Al-Waqi'ah", name_arabic: 'الواقعة', translated_name: { name: 'The Inevitable' }, verses_count: 96 },
  { id: 57, name_simple: 'Al-Hadid', name_arabic: 'الحديد', translated_name: { name: 'The Iron' }, verses_count: 29 },
  { id: 58, name_simple: 'Al-Mujadila', name_arabic: 'المجادلة', translated_name: { name: 'The Pleading Woman' }, verses_count: 22 },
  { id: 59, name_simple: 'Al-Hashr', name_arabic: 'الحشر', translated_name: { name: 'The Exile' }, verses_count: 24 },
  { id: 60, name_simple: 'Al-Mumtahanah', name_arabic: 'الممتحنة', translated_name: { name: 'She that is to be examined' }, verses_count: 13 },
  { id: 61, name_simple: 'As-Saf', name_arabic: 'الصف', translated_name: { name: 'The Ranks' }, verses_count: 14 },
  { id: 62, name_simple: "Al-Jumu'ah", name_arabic: 'الجمعة', translated_name: { name: 'Friday' }, verses_count: 11 },
  { id: 63, name_simple: 'Al-Munafiqun', name_arabic: 'المنافقون', translated_name: { name: 'The Hypocrites' }, verses_count: 11 },
  { id: 64, name_simple: 'At-Taghabun', name_arabic: 'التغابن', translated_name: { name: 'The Mutual Disillusion' }, verses_count: 18 },
  { id: 65, name_simple: 'At-Talaq', name_arabic: 'الطلاق', translated_name: { name: 'The Divorce' }, verses_count: 12 },
  { id: 66, name_simple: 'At-Tahrim', name_arabic: 'التحريم', translated_name: { name: 'The Prohibition' }, verses_count: 12 },
  { id: 67, name_simple: 'Al-Mulk', name_arabic: 'الملك', translated_name: { name: 'The Sovereignty' }, verses_count: 30 },
  { id: 68, name_simple: 'Al-Qalam', name_arabic: 'القلم', translated_name: { name: 'The Pen' }, verses_count: 52 },
  { id: 69, name_simple: 'Al-Haqqah', name_arabic: 'الحاقة', translated_name: { name: 'The Reality' }, verses_count: 52 },
  { id: 70, name_simple: "Al-Ma'arij", name_arabic: 'المعارج', translated_name: { name: 'The Ascending Stairways' }, verses_count: 44 },
  { id: 71, name_simple: 'Nuh', name_arabic: 'نوح', translated_name: { name: 'Noah' }, verses_count: 28 },
  { id: 72, name_simple: 'Al-Jinn', name_arabic: 'الجن', translated_name: { name: 'The Jinn' }, verses_count: 28 },
  { id: 73, name_simple: 'Al-Muzzammil', name_arabic: 'المزمل', translated_name: { name: 'The Enshrouded One' }, verses_count: 20 },
  { id: 74, name_simple: 'Al-Muddaththir', name_arabic: 'المدثر', translated_name: { name: 'The Cloaked One' }, verses_count: 56 },
  { id: 75, name_simple: 'Al-Qiyamah', name_arabic: 'القيامة', translated_name: { name: 'The Resurrection' }, verses_count: 40 },
  { id: 76, name_simple: 'Al-Insan', name_arabic: 'الانسان', translated_name: { name: 'The Man' }, verses_count: 31 },
  { id: 77, name_simple: 'Al-Mursalat', name_arabic: 'المرسلات', translated_name: { name: 'The Emissaries' }, verses_count: 50 },
  { id: 78, name_simple: 'An-Naba', name_arabic: 'النبإ', translated_name: { name: 'The Tidings' }, verses_count: 40 },
  { id: 79, name_simple: "An-Nazi'at", name_arabic: 'النازعات', translated_name: { name: 'Those who drag forth' }, verses_count: 46 },
  { id: 80, name_simple: "'Abasa", name_arabic: 'عبس', translated_name: { name: 'He Frowned' }, verses_count: 42 },
  { id: 81, name_simple: 'At-Takwir', name_arabic: 'التكوير', translated_name: { name: 'The Overthrowing' }, verses_count: 29 },
  { id: 82, name_simple: 'Al-Infitar', name_arabic: 'الانفطار', translated_name: { name: 'The Cleaving' }, verses_count: 19 },
  { id: 83, name_simple: 'Al-Mutaffifin', name_arabic: 'المطففين', translated_name: { name: 'The Defrauding' }, verses_count: 36 },
  { id: 84, name_simple: 'Al-Inshiqaq', name_arabic: 'الانشقاق', translated_name: { name: 'The Sundering' }, verses_count: 25 },
  { id: 85, name_simple: 'Al-Buruj', name_arabic: 'البروج', translated_name: { name: 'The Mansions of the Stars' }, verses_count: 22 },
  { id: 86, name_simple: 'At-Tariq', name_arabic: 'الطارق', translated_name: { name: 'The Nightcommer' }, verses_count: 17 },
  { id: 87, name_simple: "Al-A'la", name_arabic: 'الأعلى', translated_name: { name: 'The Most High' }, verses_count: 19 },
  { id: 88, name_simple: 'Al-Ghashiyah', name_arabic: 'الغاشية', translated_name: { name: 'The Overwhelming' }, verses_count: 26 },
  { id: 89, name_simple: 'Al-Fajr', name_arabic: 'الفجر', translated_name: { name: 'The Dawn' }, verses_count: 30 },
  { id: 90, name_simple: 'Al-Balad', name_arabic: 'البلد', translated_name: { name: 'The City' }, verses_count: 20 },
  { id: 91, name_simple: 'Ash-Shams', name_arabic: 'الشمس', translated_name: { name: 'The Sun' }, verses_count: 15 },
  { id: 92, name_simple: 'Al-Layl', name_arabic: 'الليل', translated_name: { name: 'The Night' }, verses_count: 21 },
  { id: 93, name_simple: 'Ad-Duhaa', name_arabic: 'الضحى', translated_name: { name: 'The Morning Hours' }, verses_count: 11 },
  { id: 94, name_simple: 'Ash-Sharh', name_arabic: 'الشرح', translated_name: { name: 'The Relief' }, verses_count: 8 },
  { id: 95, name_simple: 'At-Tin', name_arabic: 'التين', translated_name: { name: 'The Fig' }, verses_count: 8 },
  { id: 96, name_simple: "Al-'Alaq", name_arabic: 'العلق', translated_name: { name: 'The Clot' }, verses_count: 19 },
  { id: 97, name_simple: 'Al-Qadr', name_arabic: 'القدر', translated_name: { name: 'The Power' }, verses_count: 5 },
  { id: 98, name_simple: 'Al-Bayyinah', name_arabic: 'البينة', translated_name: { name: 'The Clear Proof' }, verses_count: 8 },
  { id: 99, name_simple: 'Az-Zalzalah', name_arabic: 'الزلزلة', translated_name: { name: 'The Earthquake' }, verses_count: 8 },
  { id: 100, name_simple: "Al-'Adiyat", name_arabic: 'العاديات', translated_name: { name: 'The Courser' }, verses_count: 11 },
  { id: 101, name_simple: "Al-Qari'ah", name_arabic: 'القارعة', translated_name: { name: 'The Calamity' }, verses_count: 11 },
  { id: 102, name_simple: 'At-Takathur', name_arabic: 'التكاثر', translated_name: { name: 'The Rivalry in world increase' }, verses_count: 8 },
  { id: 103, name_simple: "Al-'Asr", name_arabic: 'العصر', translated_name: { name: 'The Declining Day' }, verses_count: 3 },
  { id: 104, name_simple: 'Al-Humazah', name_arabic: 'الهمزة', translated_name: { name: 'The Traducer' }, verses_count: 9 },
  { id: 105, name_simple: 'Al-Fil', name_arabic: 'الفيل', translated_name: { name: 'The Elephant' }, verses_count: 5 },
  { id: 106, name_simple: 'Quraysh', name_arabic: 'قريش', translated_name: { name: 'Quraysh' }, verses_count: 4 },
  { id: 107, name_simple: "Al-Ma'un", name_arabic: 'الماعون', translated_name: { name: 'The Small Kindness' }, verses_count: 7 },
  { id: 108, name_simple: 'Al-Kawthar', name_arabic: 'الكوثر', translated_name: { name: 'The Abundance' }, verses_count: 3 },
  { id: 109, name_simple: 'Al-Kafirun', name_arabic: 'الكافرون', translated_name: { name: 'The Disbelievers' }, verses_count: 6 },
  { id: 110, name_simple: 'An-Nasr', name_arabic: 'النصر', translated_name: { name: 'The Divine Support' }, verses_count: 3 },
  { id: 111, name_simple: 'Al-Masad', name_arabic: 'المسد', translated_name: { name: 'The Palm Fiber' }, verses_count: 5 },
  { id: 112, name_simple: 'Al-Ikhlas', name_arabic: 'الإخلاص', translated_name: { name: 'The Sincerity' }, verses_count: 4 },
  { id: 113, name_simple: 'Al-Falaq', name_arabic: 'الفلق', translated_name: { name: 'The Daybreak' }, verses_count: 5 },
  { id: 114, name_simple: 'An-Nas', name_arabic: 'الناس', translated_name: { name: 'Mankind' }, verses_count: 6 },
];
